---
- name: Download DevPod CLI
  ansible.builtin.get_url:
    url: https://github.com/skevetter/devpod/releases/latest/download/devpod-linux-amd64
    dest: "{{ ansible_env.HOME }}/.local/bin/devpod"
    mode: "0755"

- name: Download DevPod Desktop deb
  ansible.builtin.get_url:
    url: https://github.com/skevetter/devpod/releases/latest/download/DevPod_linux_amd64.deb
    dest: /tmp/devpod-desktop.deb
    mode: "0644"
  when: is_desktop | bool

- name: Install DevPod Desktop
  become: true
  ansible.builtin.apt:
    deb: /tmp/devpod-desktop.deb
    state: present
  when: is_desktop | bool
